name: CI

on:
  push:
    branches:
      - main
      - ci

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt-hotspot'
          java-version: '17'
      - name: Gradle
        run: |
          chmod +x gradlew
          ./gradlew build
          mkdir tab-shifter
          cp build/libs -R tab-shifter/lib
          zip -r tab-shifter.zip tab-shifter
        
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "tab-shifter.zip"
          tag: "v${{ github.run_number }}"
